export const items = [
  {title: 'ch1ef.ru', link: 'https://ch1ef.ru', type: 'eComm'},
  {title: 'serv.severstal.com', link: 'https://serv.severstal.com', type: 'service'},
  {title: 'idea.severstal.com', link: 'https://idea.severstal.com', type: 'service'},
  {title: 'sintez-cip.ru', link: 'https://sintez-cip.ru', type: 'company'},
  {title: 'nevametal.com', link: 'https://nevametal.com', type: 'company'},
  {title: 'metiz.severstal.com', link: 'https://metiz.severstal.com', type: 'company'},
  {title: 'innovations.severstal.com', link: 'https://innovations.severstal.com', type: 'company'},
  {title: 'career.severstal.com', link: 'https://career.severstal.com', type: 'company'},
  {title: 'suppliers.severstal.com', link: 'https://suppliers.severstal.com', type: 'company'},
  {title: 'accesstyle.ru', link: 'https://accesstyle.ru', type: 'eComm'},
  {title: 'ru.dareu.com', link: 'https://ru.dareu.ru', type: 'eComm'},
  {title: 'ru.viomi.com', link: 'https://ru.viomi.com', type: 'eComm'},
  {title: 'ninetygorussia.com', link: 'https://ninetygorussia.com', type: 'eComm'},
  {title: 'fplusmobile.ru', link: 'https://fplusmobile.ru', type: 'eComm'},
  {title: 'ru.yeelight.com', link: 'https://ru.yeelight.com', type: 'eComm'},
  {title: 'jimmyglobal.ru', link: 'https://jimmyglobal.ru', type: 'eComm'},
  {title: 'ru.dreametech.com', link: 'https://ru.dreametech.com', type: 'eComm'},
  {title: 'bta-global.ru', link: 'https://bta-global.ru', type: 'eComm'},
  {title: 'vodarus.ru', link: 'https://vodarus.ru', type: 'company'},
  {title: 'gkvertikal.ru', link: 'https://gkvertikal.ru', type: 'eComm'},
  {title: 'tverdomer.ru', link: 'https://tverdomer.ru', type: 'eComm'},
  {title: 'santehnika-tut.ru', link: 'https://santehnika.ru', type: 'eComm'},
  {title: 'mb-mikro.ru', link: 'https://mb-mikro.ru', type: 'company'},

  {title: 'budet-sdelano.com'},
  {title: 'roomatic.ru'},
  {title: 'amegazavod.ru'},
  {title: 'mebel.roomatic.ru'},
  {title: 'form-perm.ru'},
  {title: 'avtomir-jac.ru'},
  {title: 'maz-ptc.ru'},
  {title: 'jacpiter.ru'},
  {title: 'steklodom.com'},
  {title: 'stadlerform.ru'},
  {title: 'adiont.ru'},
  {title: 'sigmaoptic.ru'},
  {title: 'shop.amk-troya.ru'},
  {title: 'ineo24.ru'},
  {title: 'marya.ru'},
  {title: 'proprognozy.ru'},
  {title: 'iesa.ru'},
  {title: 'pixeltools.kz'},
  {title: 'tools.pixelplus.ru'},
  {title: 'pixelplus.ru'},
  {title: 'oknastar.ru'},
  {title: 'cultfood.ru'},
  {title: 'open-urology.ru'},
  {title: 'tikkurila.moscow'},
  {title: 'mirkrasok.ru'},
  {title: 'kriston-kadastr.ru'},
  {title: 'makfa.ru'},
  {title: 'sagitta-stk.ru'},
  {title: 'tsd-atol.ru'},
  {title: 'uralz.ru'},
  {title: 'logicroof.ru'},
  {title: 'sabellino.ru'},
  {title: 'gu10.ru'},
  {title: 'gvozdhoztorg.ru'},
  {title: 'aqvalite.ru'},
  {title: 'shop.amk-troya.ru'},
  {title: 'sigmaoptic.ru'},
  {title: 'webrel.org'},
  {title: 'mydoctor32.ru'},
  {title: 'fibroblok.ru'},
  {title: 'easylex.ru'},
  {title: 'tverstroymash.ru'},
  {title: 'zolushkacleans.ru'},
  {title: 'medalis.ru'},
  {title: 'cirpp.ru'},
  {title: 'linxdatacenter.com'},
  {title: 'mcdl.ru'},
  {title: 'powervideo.ru'},
  {title: 'arbaum.ru'},
  {title: 'neolombard.ru'},
  {title: 'expodinamika.ru'},
  {title: 'onballoon.ru'},
  {title: 'rifar-store.ru'},
  {title: 'profperila.ru'},
  {title: 'trendoptika.ru'},
  {title: 'istra-cottage.ru'},
  {title: 'svetliygrad.ru'},
  {title: 'gkngo.ru'},
  {title: 'kapital-tlt.ru'},
  {title: 'cemeq.ru'},
  {title: 'pansionatu.ru'},
  {title: 'gkmonter.ru'},
  {title: 'almetplast.ru'},
  {title: 'gfk-samara.ru'},
  {title: 'russcvet.ru'},
  {title: 'zavodnizkihcen.ru'},
  {title: 'dom-na-prirode.ru'},
  {title: 'azura-tkani.ru'},
  {title: 'zub.ru'},
  {title: 'gurmario.ru'},
  {title: 'specmedtrans.ru'},
  {title: 'sr63.ru'},
  {title: 'ts-panel.ru'},
  {title: 'mebel-dolina.ru'},
  {title: 'dabbler.ru'},
  {title: 'lorinfo.ru'},
  {title: 'volgorost.ru'},
  {title: 'dugovik.ru'},
  {title: 'teswel.ru'},
  {title: 'pansion.life'},
  {title: 'company-okna.ru'},
  {title: 'surdobox.ru'},
  {title: 'stax-detailing.ru'},
  {title: 'luka-samara.ru'},
  {title: 'greenbag-camp.ru'},
  {title: 'rus-extract.com'},
  {title: 'doma-prestarelye.ru'},
  {title: 'wgs-gcvep.ru'},
  {title: 'stroydarom.ru'},
  {title: 'plintus-hall.ru'},
  {title: 'pol360.ru'},
  {title: 'remonstr.ru'},
  {title: 'pansionat-zabota24.ru'},
  {title: 'ckbran.ru'},
  {title: 'np-sp.ru'},
  {title: 'mirpolovspb.ru'},
  {title: 'ru-gps.ru'},
  {title: 'tehnar.ru'},
  {title: 'fusion-chrome.ru'},
  {title: 'ремонт-теплица.рф'},
  {title: 'online-lowrance.ru'},
  {title: 'fusiontech.ru'},
  {title: 'rhinodesign.ru'},
  {title: 'novtecas.ru'},
  {title: 'eco2b.ru'},
  {title: 'kavcosmo.ru'},
  {title: 'atcgaz.ru'},
  {title: 'archdetali.ru'},
  {title: 'alphaservice24.com'},
  {title: 'keratinvolos.ru'},
  {title: 'moscow-klining.ru'},
  {title: 'superpirogi.ru'},
  {title: 'southmedia.ru'},
  {title: 'wildjam.ru'},
  {title: 'paoloconte.ru'},
  {title: 'rgsl.ru'},
  {title: '1c-wiseadvice.ru'},
  {title: 'b2b.gauss.ru'},
  {title: 'kwork.ru'},
  {title: 'eurocran.su'},
  {title: 'sibirthegame.ru'},
  {title: 'strike-active.ru'},
  {title: 'kupisad.ru'},
  {title: 'chefbanda.ru'},
  {title: 'tdo.ru'},
  {title: 'velomirshop.ru'},
  {title: 'kovalev.ru'},
  {title: 'maconsulting.ru'},
  {title: 'deluxe-cotton.ru'},
  {title: 'kick.game'},
  {title: 'groentec.ru'},
  {title: 'gsprom.ru'},
  {title: '1c-rarus.com'},
  {title: 'elevel.ru'},
  {title: 'gidratop.ru'},
  {title: 'relaxa.ru'},
  {title: 'iondom.ru'},
  {title: 'woldom.ru'},
  {title: 'dentoptics.digital'},
  {title: 'alternativa-s.com'},
  {title: 'avionagro.ru'},
  {title: 'dialogdent.ru'},
  {title: 'malinkacapital.com'},
  {title: 'onespace.pro'},
  {title: 'storedent.ru'},
  {title: 'samara.dental'},
  {title: 'ascondicioner.ru'},
  {title: 'tp.info-pro.ru'},
  {title: 'samara-soft.ru'},
  {title: 'info-pro.ru'},
  {title: 'lk.energo-vympel.ru'},
  {title: 'one-fit.ru'},
  {title: 'samkarniz.ru'},
  {title: 'gazprombank.ru'},
  {title: 'bunnygummy.ru'},
  {title: 'megasmokers.ru'},
  {title: 'goodtime555.ru'},
  {title: 'ericthered.ru'},
  {title: 'ramayoga.ru'},
  {title: 'trast-avto.ru'},
  {title: 'domostroi.ru'},
  {title: 'kamkp.ru'},
  {title: 'redsoft.ru'},
  {title: 'sam-argo.ru'},
  {title: 'klever96.ru'},
  {title: 'la-parisienne.ru'},
  {title: 'justsmile.club'},
  {title: 'fitness.kinup.ru'},
  {title: 'botek-fitness.club'},
  {title: 'tehnoprojekt.ru'},
  {title: 'klapshtos.pro'},
  {title: 'palubacafe.ru'},
  {title: 'siven63.ru'},
  {title: 'delta-eco.ru'},
  {title: 'marrakesh.kinup.ru'},
  {title: 'kinup.ru'},
  {title: 'zolotoykod.ru'},
  {title: 'termoclick.ru'},
  {title: 'zuweb.ru'},
  {title: 'zu63.ru'}
]