lang: 'ru'
locale: 'ru'
title: 'Sergei ★ Česnakas'
author: 'Sergei ★ Česnakas'
description: 'Web Developer'
name: 'Sergei ★ Česnakas'
google_analytics: G-FCN777R7BQ
yandex_site_verification: '70155283'

gtag: "
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FCN777R7BQ"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FCN777R7BQ');
  </script>"

include: ["/_includes/google-analytics.html"]